df[
    [
        "user_id",
        "name",
        "description",
        "avatar",
        "address",
        "start_time",
        "end_time",
        "duration",
        "min_cost",
        "max_cost",
    ]
] = df_profile[
    [
        "user_id",
        "name",
        "description",
        "avatar",
        "location",
        "start_time",
        "end_time",
        "duration",
        "min_cost",
        "max_cost",
    ]
]
